logging:
  level:
    com.example.consumingwebservice: INFO
    org:
      springframework:
        ws: DEBUG

# USEFUL NOTE: here we can simply change DEBUG level for particular package to get more info without putting log messages in code